# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: dancinLlama's Blog
email: "jwl007 at gmail dot com"
description: >- # this means to ignore newlines until "baseurl:"
  A blog on software.  Focused on Salesforce development, deployment, and integrations.
twitter_username: dancinllama
github_username: dancinllama
minimal_mistakes_skin: air
search: true
url                      : https://dancinllama.github.io 

repository               : "dancinllama/dancinllama.github.io"

comments:
  provider               : "utterances"
  utterances:
    theme                : "github-light"
    issue_term           : "pathname"
    repo                 : "dancinllama/dancinllama.github.io"
    repository           : "dancinllama/dancinllama.github.io"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "James Loghry"
  avatar : "https://en.gravatar.com/userimage/36823894/b2a7029d51a7e4ae81d1201580de472b.png"
  bio    : "Salesforce Architect / Developer @ Demand Chain. SI Partner. Salesforce MVP Hall of Fame 2013-2019"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.demandchain.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/dancinllama"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dancinllama"
    
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/dancinllama"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/dancinllama"
    
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
